name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
    inputs:
      access_id:
        description: 'access id token'     
        required: true
        default: 'input access id token'
      secret_id:
        description: 'secret id token'     
        required: true
        default: 'secret access id token'
jobs:
  authentication:
    runs-on: ubuntu-latest
    outputs:
      accessID: "${{ steps.auth.outputs.id }}"
      secretID: "${{ steps.auth.outputs.st }}"
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Auth
        id: auth
        run: |
            access=$(cat $GITHUB_EVENT_PATH | jq '.inputs.access_id' | sed 's/"//g' )
            secret=$(cat $GITHUB_EVENT_PATH | jq '.inputs.secret_id' | sed 's/"//g' )
            # echo "::add-mask::$access"
            # echo "::add-mask::$secret"
            echo "id=$access" >> "$GITHUB_OUTPUT"
            echo "st=$secret" >> "$GITHUB_OUTPUT"
      # - name: Terraform Init
      #   id: init
      #   run: terraform init

      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color

      # - name: Terraform Plan
      #   id: plan
      #   run: |
      #       export AWS_ACCESS_KEY_ID=${{ steps.auth.outputs.accessID }}
      #       export AWS_SECRET_ACCESS_KEY=${{ steps.auth.outputs.secretID }}
      #       export AWS_REGION="eu-north-1"
      #       terraform plan
      #   continue-on-error: true
  terraform:
    needs:
      - authentication
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: terraform init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: |
            export AWS_ACCESS_KEY_ID=${{ needs.authentication.outputs.accessID }}
            export AWS_SECRET_ACCESS_KEY=${{ needs.authentication.outputs.secretID }}
            export AWS_REGION=eu-north-1
        continue-on-error: true

