name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  


jobs:
  terraformrun:
    runs-on: ubuntu-latest
    # environment: 
    #   name: test
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Group of log lines
        env:
          id: ${{ secrets.ID }}
          secret: ${{ secrets.SECRET }}
        run: |
            # echo "::group::My title"
            # echo "Inside group"
            # # pwd
            # # ls
            # # terraform -v
            # echo $ID$SECRET
            # echo ${{ secrets.TEST }}${{ secrets.ID }}${{ secrets.SECRET }}
            # echo ${{ secrets.ID }}
            # echo ${{ secrets.SECRET }}
            export AWS_ACCESS_KEY_ID=$id
            export AWS_SECRET_ACCESS_KEY=$secret
            export AWS_REGION="eu-north-1"
            # terraform init
            # terraform ${{ inputs.tags }} -auto-approve


      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
            terraform plan
        continue-on-error: true
