name: secret-creation-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  authentication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Testing secret
        id: secret
        run: |
          echo 'helloworldsodjwiqojdwjdihwduwqdoiwqjdoiwqjdijqwoidjoiJWQOIDJOqjdow' > test
          base64 test > file
          secret=$(cat file)
          echo $secret
          echo "::set-output name=secret::$secret"
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'helloworld'
          value: '$secret'
          repository: 'cbortici/k8s'
          token: ${{ secrets.TEST }}
      - name: verifying secret
        run: |
          echo -n "${{ secrets.WORKLOAD }}" >> foo && cut -c1-3 foo && cut -c4
          echo "added on ${{steps.secret.outputs.secret}}"
