name: secret-creation-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  authentication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'helloworld'
          value: 'secretvalue'
          repository: 'cbortici/k8s'
          token: ${{ secrets.TEST }}

