name: secret-creation-test
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
jobs:
  authentication:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Testing secret
        run: |
          echo 'helloworld' > test
          base64 test > file
          secret=$(cat file)
          echo $secret
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'helloworld'
          value: 'thisisatestsecret'
          repository: 'cbortici/k8s'
          token: ${{ secrets.TEST }}
      - name: verifying secret
        run: |
          echo ${{ secrets.HELLOWORLD }} | sed 's/./& /g'

