name: Terraform test

on: 
  workflow_dispatch:

jobs:
  inform_about_apply:
    name: Inform About Apply
    runs-on: ubuntu-20.04

    steps:
      - name: Inform on PR that Apply is Running
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ***Running terraform apply***
            Results will display here momentarily...

  plan_and_apply:
    name: Plan and Apply
    # env:
    #   TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
    runs-on: ubuntu-20.04
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     path:
    #       - dev
    #       - stage
    #       - prod

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup helm
        uses: azure/setup-helm@v4.2.0

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.ID }}
          aws-secret-access-key: ${{ secrets.SECRET }}

      - name: Initialize Terraform
        run: |
            cd boex/boex_dev_terraform
            terraform init -reconfigure -backend-config="bucket=boexstfstatebucket" -backend-config="key=boexterraform.tfstate" -backend-config="region=eu-central-1"

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
          export TF_VAR_aws_secret_key=${{ secrets.SECRET }}
          export TF_VAR_aws_access_key=${{ secrets.ID }}
          cd boex/boex_dev_terraform
          echo "${{ secrets.SERVER }}" | base64 --decode > kube_config_server.yaml
          echo "YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIG5hbWU6ICJjbHVzdGVyLWs4cyIKICBjbHVzdGVyOgogICAgc2VydmVyOiAiaHR0cHM6Ly9yYW5jaGVyLjM0LjIyMS4xMzMuMjM2LnNzbGlwLmlvL2s4cy9jbHVzdGVycy9jLW0tNmd0MmwybTgiCiAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHktZGF0YTogIkxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUoyUkVORFFcCiAgICAgIFZkUFowRjNTVUpCWjBsQ1FVUkJTMEpuWjNGb2EycFBVRkZSUkVGcVFrZE5VbmQzUjJkWlJGWlJVVXRGZUU1clpWYzFhR0pYYkdvS1lcCiAgICAgIGtkc2VtUkhWblZhV0VsMFlqTktiazFUV1hkS1FWbEVWbEZSUkVSQ01XdGxWelZvWWxkc2FtSkhiSHBrUjFaMVdsaEpkRmt5UmtGTlZcCiAgICAgIEdONFRtcEpkd3BPVkdNeFRWUkJaVVozTUhsT1JFRXhUV3BCZUUxVVVUVk5WRVpoUm5jd2VrNUVRVEZOVkdkNFRWUlJOVTFVUm1GTlJcCiAgICAgIFZsNFNFUkJZVUpuVGxaQ1FXOVVDa1V5VWpWaWJVWjBZVmRPYzJGWVRqQmFWelZzWTJreGRtTnRZM2hLYWtGclFtZE9Wa0pCVFUxSVZcCiAgICAgIDFJMVltMUdkR0ZYVG5OaFdFNHdXbGMxYkdOcE1Xb0tXVlZCZUU1NlJUSk5ha0V4VG5wVmVFMUdhM2RGZDFsSVMyOWFTWHBxTUVOQlVcCiAgICAgIFZsSlMyOWFTWHBxTUVSQlVXTkVVV2RCUlc5TWNqZzFTRTE1VHpoVFNRcFBRVXB5TmtNelJrNTNZMVJaZG13eWN6ZGxZVkpVUWxSNFVcCiAgICAgIDJsWGFqTmtPR0YyYjB0NU4xSjFVazltVHpaa1ZXMTFkRkpSVVZFMFoyTmhhakY2WW5GekNsQmllVWM0S3paNldIRk9RMDFGUVhkRVpcCiAgICAgIDFsRVZsSXdVRUZSU0M5Q1FWRkVRV2RMYTAxQk9FZEJNVlZrUlhkRlFpOTNVVVpOUVUxQ1FXWTRkMGhSV1VRS1ZsSXdUMEpDV1VWR1RcCiAgICAgIHpOc2RHdGFSRlJIVURoak1XczJSRkZsWmxCR1RHMU5UbUk0VFVGdlIwTkRjVWRUVFRRNVFrRk5RMEV3WTBGTlJWRkRTVVkzUmdwamNcCiAgICAgIGtZeVMxaGtWRlpDZVZsTVVEVk9RbWxaYlc5TlJuTXlaWGwwWmxKdFdXbFZia1E0WTFoeVFXbENSMm8yYUVkNVdVRnZTMk56UmpOV1lcCiAgICAgIDNkQ2FGQm9Da2RVZUhWQk9VMXFZMUpJZG1KclJIWlZPV3d2VG5jOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdCIKCnVzZXJzOgotIG5hbWU6ICJjbHVzdGVyLWs4cyIKICB1c2VyOgogICAgdG9rZW46ICJrdWJlY29uZmlnLXVzZXItYnhoYjh0czljNzo0cHNzZmd6bnBsbGZnc2hjcjIyNHY3bXZremNrbTJoZ2dmYnYyMnBsMnFocnZ6cTVjczQ0ODgiCgoKY29udGV4dHM6Ci0gbmFtZTogImNsdXN0ZXItazhzIgogIGNvbnRleHQ6CiAgICB1c2VyOiAiY2x1c3Rlci1rOHMiCiAgICBjbHVzdGVyOiAiY2x1c3Rlci1rOHMiCgpjdXJyZW50LWNvbnRleHQ6ICJjbHVzdGVyLWs4cyI=" | base64 --decode > kube_config_workload.yaml
          ls -l
          set +e
          terraform plan -detailed-exitcode -input=false -out=tfplan
          exit_code=$?
          set -e
          if [ $exit_code -eq 1 ]; then
            echo "There are pending changes."
            exit 0
          fi
        

      # Sed is taking all lines that begin with one or more spaces followed by a `+` or `-`.
      # It stores the amount of spaces in `\1` and the +/- in `\2`.
      # Then replace that portion of the line with `\2\1` (+/- followed by the number of matched spaces).
      - name: Reformat Plan
        if: steps.plan.outcome == 'success'
        run: |
          echo '${{ steps.plan.outputs.stderr }}' > plan.txt

      - name: Put Plan in Env Var
        if: steps.plan.outcome == 'success'
        run: |
          PLAN=$(cat plan.txt)
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "$PLAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Apply Terraform
        if: steps.plan.outcome == 'success'
        id: apply
        run: |
          export TF_VAR_aws_secret_key=${{ secrets.SECRET }}
          export TF_VAR_aws_access_key=${{ secrets.ID }}
          cd boex/boex_dev_terraform
          # terraform apply \
          #   -input=false \
          #   -no-color \
          #   tfplan
          # base64 kube_config_server.yaml > server
          # base64 kube_config_workload.yaml > workload
          # server=$(cat server)
          # workload=$(cat workload)
          # echo "::set-output name=server::$server"
          # echo "::set-output name=workload::$workload"
          # echo "${{ secrets.SERVER }}" | base64 --decode > kube_config_server.yaml
          # echo "::set-output name=server::${{ secrets.SERVER }}"
          # echo "${{ secrets.WORKLOAD }}" | base64 --decode > kube_config_workload.yaml
          # echo "::set-output name=workload::${{ secrets.WORKLOAD }}"
          # ls
          # cat kube_config_server.yaml
          # cat kube_config_workload.yaml
          # echo "added on ${{steps.apply.outputs.workload}}"
          # terraform apply --auto-approve
          # base64 kube_config_server.yaml > server
          # base64 kube_config_workload.yaml > workload
          # server=$(cat server)
          # workload=$(cat workload)
          # echo "::set-output name=server::$server"
          # echo "::set-output name=workload::$workload"
          # cat server
          # cat workload
          # terraform apply -target=module.rancher-server.local_file.kube_config_server_yaml --auto-approve
          # terraform apply -target=module.rancher-server.local_file.kube_config_workload_yaml --auto-approve
          # terraform apply --auto-approve
          echo "${{ secrets.SERVER }}" | base64 --decode > kube_config_server.yaml
          echo "YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnCmNsdXN0ZXJzOgotIG5hbWU6ICJjbHVzdGVyLWs4cyIKICBjbHVzdGVyOgogICAgc2VydmVyOiAiaHR0cHM6Ly9yYW5jaGVyLjM0LjIyMS4xMzMuMjM2LnNzbGlwLmlvL2s4cy9jbHVzdGVycy9jLW0tNmd0MmwybTgiCiAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHktZGF0YTogIkxTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUoyUkVORFFcCiAgICAgIFZkUFowRjNTVUpCWjBsQ1FVUkJTMEpuWjNGb2EycFBVRkZSUkVGcVFrZE5VbmQzUjJkWlJGWlJVVXRGZUU1clpWYzFhR0pYYkdvS1lcCiAgICAgIGtkc2VtUkhWblZhV0VsMFlqTktiazFUV1hkS1FWbEVWbEZSUkVSQ01XdGxWelZvWWxkc2FtSkhiSHBrUjFaMVdsaEpkRmt5UmtGTlZcCiAgICAgIEdONFRtcEpkd3BPVkdNeFRWUkJaVVozTUhsT1JFRXhUV3BCZUUxVVVUVk5WRVpoUm5jd2VrNUVRVEZOVkdkNFRWUlJOVTFVUm1GTlJcCiAgICAgIFZsNFNFUkJZVUpuVGxaQ1FXOVVDa1V5VWpWaWJVWjBZVmRPYzJGWVRqQmFWelZzWTJreGRtTnRZM2hLYWtGclFtZE9Wa0pCVFUxSVZcCiAgICAgIDFJMVltMUdkR0ZYVG5OaFdFNHdXbGMxYkdOcE1Xb0tXVlZCZUU1NlJUSk5ha0V4VG5wVmVFMUdhM2RGZDFsSVMyOWFTWHBxTUVOQlVcCiAgICAgIFZsSlMyOWFTWHBxTUVSQlVXTkVVV2RCUlc5TWNqZzFTRTE1VHpoVFNRcFBRVXB5TmtNelJrNTNZMVJaZG13eWN6ZGxZVkpVUWxSNFVcCiAgICAgIDJsWGFqTmtPR0YyYjB0NU4xSjFVazltVHpaa1ZXMTFkRkpSVVZFMFoyTmhhakY2WW5GekNsQmllVWM0S3paNldIRk9RMDFGUVhkRVpcCiAgICAgIDFsRVZsSXdVRUZSU0M5Q1FWRkVRV2RMYTAxQk9FZEJNVlZrUlhkRlFpOTNVVVpOUVUxQ1FXWTRkMGhSV1VRS1ZsSXdUMEpDV1VWR1RcCiAgICAgIHpOc2RHdGFSRlJIVURoak1XczJSRkZsWmxCR1RHMU5UbUk0VFVGdlIwTkRjVWRUVFRRNVFrRk5RMEV3WTBGTlJWRkRTVVkzUmdwamNcCiAgICAgIGtZeVMxaGtWRlpDZVZsTVVEVk9RbWxaYlc5TlJuTXlaWGwwWmxKdFdXbFZia1E0WTFoeVFXbENSMm8yYUVkNVdVRnZTMk56UmpOV1lcCiAgICAgIDNkQ2FGQm9Da2RVZUhWQk9VMXFZMUpJZG1KclJIWlZPV3d2VG5jOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdCIKCnVzZXJzOgotIG5hbWU6ICJjbHVzdGVyLWs4cyIKICB1c2VyOgogICAgdG9rZW46ICJrdWJlY29uZmlnLXVzZXItYnhoYjh0czljNzo0cHNzZmd6bnBsbGZnc2hjcjIyNHY3bXZremNrbTJoZ2dmYnYyMnBsMnFocnZ6cTVjczQ0ODgiCgoKY29udGV4dHM6Ci0gbmFtZTogImNsdXN0ZXItazhzIgogIGNvbnRleHQ6CiAgICB1c2VyOiAiY2x1c3Rlci1rOHMiCiAgICBjbHVzdGVyOiAiY2x1c3Rlci1rOHMiCgpjdXJyZW50LWNvbnRleHQ6ICJjbHVzdGVyLWs4cyI=" | base64 --decode > kube_config_workload.yaml
          while terraform destroy --auto-approve; [[ $? -ne 0 ]];
          do
          echo "Result unsuccessful"
          sleep 1
          done
          echo "successfully destroyed"
      # - uses: hmanzur/actions-set-secret@v2.0.0
      #   with:
      #     name: 'SERVER'
      #     value: '$server'
      #     repository: 'cbortici/k8s'
      #     token: ${{ secrets.TEST }}
      # - uses: hmanzur/actions-set-secret@v2.0.0
      #   with:
      #     name: 'WORKLOAD'
      #     value: '$workload'
      #     repository: 'cbortici/k8s'
      #     token: ${{ secrets.TEST }}

      - name: Post Plan and Apply to GitHub PR
        if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Applying **PROD**:

            ```diff
            echo ${{ env.PLAN }} no errors
            ```

            ```
            ${{ steps.apply.outputs.stdout }}
            ```

      - name: Post Plan Failure
        if: steps.plan.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Plan failed for **PROD**:

            ```
            ${{ steps.plan.outputs.stderr }}
            ```

      - name: Post Apply Failure
        if: steps.apply.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.TEST }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            Apply failed for **PROD**:

            ```
            ${{ steps.apply.outputs.stderr }}
            ```