name: Test
on:
  workflow_dispatch:
    inputs:
      access_id:
        description: 'access id token'     
        required: true
        default: 'input access id token'

jobs:
  one:
    runs-on: ubuntu-latest
    outputs:
      HELLO: "${{ steps.set-some-stuff.outputs.${{ inputs.access_id }} }}"
    steps:
      - name: one-1
        id: set-some-stuff
        run: |
          # echo "HELLO=${{ inputs.access_id }}" >> "$GITHUB_OUTPUT"
          echo "::add-mask::${{ inputs.access_id }}" >> "$GITHUB_OUTPUT"
      - name: one-2
        run: |
          echo "${{steps.set-some-stuff.outputs.HELLO}}"
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: two-1
        run: |
          echo "${{ needs.one.outputs.HELLO }}"